server:
  port: 8080

spring:
  application:
    name: ldap-auth-wrapper

  mail:
    host: smtp.example.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.example.com

  cache:
    type: simple

logging:
  level:
    root: INFO
    com.nikhilkarn: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

security:
  api-key: ${API_KEY:nikhil-api-key-123}
  bearer-token: ${BEARER_TOKEN:valid-secure-token}
